name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '17 2 * * *'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 17
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - node-version: 16
            os: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
      - run: npm run eslint
        if: ${{ matrix.node-version == '16' && matrix.os == 'ubuntu-latest' }}
      - name: Publish codeclimate code coverage
        if: ${{ matrix.node-version == '16' && matrix.os == 'ubuntu-latest' }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 150be11cde8a18d41d37df6c31823d35892fdd1dbf79c969142c6b3033104e46
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
